# Generated by Django 5.0.3 on 2024-03-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('sinopse', models.CharField(max_length=1000)),
                ('genero', models.CharField(max_length=30)),
                ('ano', models.IntegerField(max_length=4)),
                ('diretor', models.CharField(max_length=150)),
            ],
        ),
    ]
